#! /usr/bin/python

import simplejson, sys, os.path
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
import pymovex

pymovex.debug(False)

with open("prefs.json") as f:
    prefs = simplejson.loads(f.read())

pymovex.connect("OIS320MI", **prefs['connect'])

# CONO	16	18	3	N	1	Company
# FACI	19	21	3	A	1	Facility
# CUNO	22	31	10	A	1	Customer number
# ITNO	32	46	15	A	1	Item number
# WHLO	47	49	3	A		Warehouse location
# ORDT	50	59	10	D		Order date
# ORQA	60	75	16	N		Ordered quantity
# ALUN	76	78	3	A		Alternate unit of measurement
# CUCD	79	81	3	A		Currency
# ORTP	82	84	3	A		Order type
# PRRF	85	86	2	A		Price list
# DISY	87	96	10	A		Discount model
# DWDT	97	106	10	N		Requested delivery date
# CFIN	107	113	7	N		Configuration number
# CAMA	114	114	1	N		Calculate markups
# ATNR	115	131	17	N		Attribute number


output_fields = ('WHLO', 'SAPR', 'LNAM', 'ORDT', 'ORQA', 'ORQS', 'PRRF', 'SMCD', 'ORTP', 'AAGN',
'BAGN', 'DISY', 'CUCD', 'ALUN', 'PRMO', 'SPUN', 'SACD', 'PRRO', 'CMNO', 'DIA1',
'DIA2', 'DIA3', 'DIA4', 'DIA5', 'DIA6', 'DIC1', 'DIC2', 'DIC3', 'DIC4', 'DIC5',
'DIC6', 'CMP1', 'CMP2', 'CMP3', 'CMP4', 'CMP5', 'CMP6', 'TX81', 'TX82', 'TX83',
'TX84', 'TX85', 'TX86', 'CHL1', 'CHL2', 'CHL3', 'CHL4', 'CHL5', 'CHL6', 'SAC2')

#pymovex.rawquery("GetPriceLine   900   41004201  000040")
#pymovex.rawquery("GetPriceLine   900   00000040  123440")

args = sys.argv[1:]
for k, v in pymovex.fquery_single("GetPriceLine", {"CONO": prefs['globals']['CONO'], "CUNO": args[0], "ITNO": args[1], "ORQA": args[2]}, output_fields).items():
    print k, v
#print pymovex.fquery_single("GetPriceLine", {"CONO": prefs['globals']['CONO'], "CUNO": "000040", "ITNO": "41004201"}, output_fields)

pymovex.close()
