#! /usr/bin/python

import simplejson, sys, os.path
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
import pymovex

with open("prefs.json") as f:
    prefs = simplejson.loads(f.read())

pymovex.connect("CRS610MI", **prefs['connect'])

pymovex.maxrec(10)
for i, result in enumerate(pymovex.fquery("LstByName", {"CONO": prefs['globals']['CONO']}, ('CUNO',))):
    print "%-3s"%i, result
pymovex.close()
