#! /usr/bin/python

import simplejson, sys, os.path
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
import pymovex

with open(sys.argv[1]) as f:
    prefs = simplejson.loads(f.read())

pymovex.connect("MMS200MI", **prefs['connect'])
pymovex.maxrec(0)

cols = ('STAT', 'ITNO', 'ITDS', 'CFI1')
print ";".join(cols)

# will not fetch all items thanks to the use of a generator
for i, result in enumerate(pymovex.fquery("LstItmByItm", {'CONO': prefs['globals']['CONO']}, cols)):
    print ";".join(result.values())

pymovex.close()
