#! /usr/bin/python

import simplejson, sys, os.path
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
import pymovex

with open("prefs.json") as f:
    prefs = simplejson.loads(f.read())

args = sys.argv[1:]
pymovex.connect("PPS100MI", **prefs['connect'])

fields = ('SUNO', 'AGNB', 'OBV1', 'GRPI', 'FVDT', 'AGQT', 'PUQT', 'PUPR')
print ";".join(fields)
for v in pymovex.fquery("LstAgrLine", {"CONO": prefs['globals']['CONO'], "SUNO": args[0], "AGNB": args[1]}, fields):
    print ";".join(v.values())

pymovex.close()
