#! /usr/bin/python

import simplejson
import pymovex
program = "CRS610MI"
with open("prefs.json") as f:
    prefs = simplejson.loads(f.read())
pymovex.connect(program, **prefs['connect'])

pymovex.maxrec(10)
for i, result in enumerate(pymovex.fquery("LstByName", {"CONO": prefs['globals']['CONO']}, ('CUNO',))):
    print "%-3s"%i, result
pymovex.close()
