#! /usr/bin/python

import simplejson, sys, os.path
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
import pymovex

with open("prefs.json") as f:
    prefs = simplejson.loads(f.read())

pymovex.connect("MMS200MI", **prefs['connect'])
pymovex.maxrec(1000000)

# will not fetch so many items thanks to the use of a generator
for i, result in enumerate(pymovex.fquery("LstItmByItm", {'CONO': prefs['globals']['CONO']}, ('STAT', 'ITDS', 'FUDS', 'ITNO'))):
    print "%-3s"%i, result
    if i==100:
        break

pymovex.close()
