#! /usr/bin/python

import simplejson
import pymovex
program = "CRS610MI"
with open("prefs.json") as f:
    prefs = simplejson.loads(f.read())
pymovex.connect(program, **prefs)

# "LstByGroup"
pymovex.maxrec(10)

pymovex.close()
