#! /usr/bin/python

import simplejson, sys, os.path
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
import pymovex

with open("prefs.json") as f:
    prefs = simplejson.loads(f.read())

args = sys.argv[1:]
pymovex.connect("PPS100MI", **prefs['connect'])

fields = ('SUNO', 'AGNB', 'OBV1', 'GRPI', 'FVDT', 'AGQT', 'PUPR', 'PUCD', 'DIP3')

# Skip headers
line = sys.stdin.readline()

while True:
    line = sys.stdin.readline()
    if line == '':
        break
    line = line.rstrip()
    values = line.split(';')
    data = {}
    for i, key in enumerate(fields):
        data[key] = values[i]

    args = {"CONO": prefs['globals']['CONO']}
    args.update(data)
    print data
    pymovex.fquery_single("UpdAgrLine", args, ())

pymovex.close()
