#! /usr/bin/python

import simplejson, sys, os.path
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
import pymovex
import openpyxl

with open("prefs.json") as f:
    prefs = simplejson.loads(f.read())

cmd_args = sys.argv[1:]
wb = openpyxl.reader.excel.load_workbook(cmd_args[0])
sheet = wb.get_active_sheet()

pymovex.connect("PPS100MI", **prefs['connect'])

fields = ('SUNO', 'AGNB', 'FVDT', 'OBV1', 'GRPI', 'PUPR', 'PUCD', 'DIP3', 'AGQT', 'FRQT')

# Skip first two lines
for row in sheet.rows[2:]:
    data = {}
    for i, key in enumerate(fields):
        data[key] = row[i].value

    data['GRPI'] = str(data['GRPI'])
    data['OBV1'] = str(data['OBV1'])

    assert len(data['GRPI']) == 2
    assert len(data['OBV1']) == 6

    args = {"CONO": prefs['globals']['CONO']}
    args.update(data)

    args1 = dict(args)
    del args1['FRQT']

    args2 = dict(args)
    args2['PUPR'] = args2['PUPR'] / args2['PUCD']
    del args2['AGQT']
    del args2['PUCD']

    #print "UpdAgrLine", args1
    #pymovex.fquery_single("UpdAgrLine", args1, ())
    print "UpdStgPrice", args2
    #pymovex.fquery_single("UpdStgPrice", args2, ())

pymovex.close()
